### ISSUE TITLE
Lasair Cycle-11 Oct'24 to Mar'25

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair#313]
See also notes from [25/SEP/24](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3735781377/25+September+2024) Lasair fortnightly meeting.

Cycle 11 begins at the start of October 2024 (PM64) and finishes at the end of March 25 (PM69). 

In order of priority, the activities, deliverables and milestones agreed as due in this cycle are as follows.

- [x] 0. Get ready for Operation Rehearsal 5, end of Feb

- [x] 1. Cutout image ingestion (@genghisken / @gpfrancis / @thespacedoctor )
    - [x] a. Reliability and optimisation
    - [x] b. Reaper for cutout images
    - [x] c.  How to fetch cutout images from Rubin (subject to availability)

- [ ] 2. Sherlock: 
     - [x] a. Ingest Delve, Gaia, catalogues ( @thespacedoctor  )
    -  [ ] b. Deep drilling fields from cosmology surveys i.e. ESO DECAM etc (see Josh W)

- [x] 3.  ZTF data release in the DAC ( @RoyWilliams )
    - [x] a.  Start with 18 fields RA 13h-14h and Dec -10 to 10.
   
- [x] 4. Features
    - [x] a. Revision of [Features](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3188195339) list ( @RoyWilliams ) 
    - [x] b. Compare features for utility
    - [ ] c. Integrate Fastfinder (  @genghisken / @RoyWilliams /Michael Fulton )

- [ ] 5. Profile and improve database resilience and scalability ( @genghisken / @thespacedoctor   /  @gpfrancis )

- [ ] 6. Performance Evaluation ( @gpfrancis / @genghisken / @RoyWilliams / @thespacedoctor )
    - [x] a. Integrate simulated alert distribution from USDF
    - [ ] b. see also [Scaling & profile experiments ticket](https://github.com/lsst-uk/lasair-project-management/issues/258) below
    
 - [ ] 7. Add Fermi GBM alerts to GW infra – ingesting Healpix ( @RoyWilliams )
 
 - [x] 8. Oxford Lasair meeting, Oxford, January 2025
    - [x] a. Preparations for ( @RoyWilliams  )

- [x] 9. Maintenance and continued operation of the ZTF pipeline, databases, and website
    - [x] a. Lasair4 maintenance issue - Migrating everything that is still on Ubuntu 20.04 to24.04 before April 2025. This needs specifically to be addressed in the next 6 months.   ( @gpfrancis )

Note:  if any items are left over from previous cycle then these are shown as tickets below

**Comment by tms-epcc** [comment]
25/SEP/24
- initial draft of ticket and plan (see description above) following Lasair fortnightly meeting
- @RoyWilliams - is this ok or are changes needed? When you are ok, I will add rest of the Lasair team to the assignees list.

**Comment by RoyWilliams** [comment]
Looks good Terry. Thank you as always for converting a sow's ear to a silk purse!

**Comment by RoyWilliams** [comment]
Terry, can we add another:
9. Maintenance and continued operation of the ZTF pipeline, databases, and website

**Comment by gpfrancis** [comment]
The lasair4 maintenance issue that we need to address specifically in the next 6 months is migrating everything that is still on Ubuntu 20.04 before April 2025.

**Comment by tms-epcc** [comment]
20/NOV/24 
1. Cutout image ingestion - Cutouts will not be an issue after all, rather it is the catalogs
2. Sherlock - no news
3. ZTF in the DAC - on the test RSP but not yet on the production RSP.  If tell astro community then it would mean them using the test RSP which is not  what it is for.  Roy will discuss more with Gareth.  
4. Features - some progress with features; no movement yet on Fastfinder but Stephen ok with BBB if necessary; extinction map enables query on the extinction number(see https://github.com/lsst-uk/lasair-lsst/pull/210);
5. Profile and improve database resilience and scalability - some fixes made, timeout changes help with resilience but overall the approach feels arbitrary. Ken still going through the Data Stack tutorials to help with strategy.  
6. Performance Evaluation - no news on simulated alerts since 30/SEP/24; will speak more with Eric in January.
7. Add Fermi GBM alerts to GW infra – Dave dealt with Healpix on Atlas so will discuss with him
8. Oxford meeting - need to send list to Lasair users 
9. ZTF ops and maintenance - some PRs applied to Lasair ZTF (external brokers - https://github.com/lsst-uk/lasair4/pull/230, URLs https://github.com/lsst-uk/lasair4/pull/229). Need to apply these to Lasair-LSST too
10. Lasair4 and ubuntu - this is with Gareth

**Comment by tms-epcc** [comment]
04/DEC/24
1. Cutout image ingestion - Some issues
2. Sherlock - Deep drilling fields in progress
3. ZTF in the DAC- Now need astronomy community to use and provide feedback.  Need to agree whom to contact first . Ask LUG.
4. Features - BBB being turned into a package - will get definitive confirmation from Stephen.  No news on FF.
5. Profile and improve database resilience and scalability -  need some news from Ken
6. Performance Evaluation - see above
7. Add Fermi GBM alerts to GW infra - getting more GBM alerts than originally expected.  Had expected 1 per week but getting handful per day.  Have meetings lined up with relevant experts to decide on way forward.
8. Oxford mtg - 32 registrations so far, most in person
9. ZTF ops and maintenance  - to be discussed
10. Lasair4 & Ubuntu upgrade - to be discussed

**Comment by tms-epcc** [comment]
18/DEC/24
4. BBB is now included as package but Roy concerned users will be swamped by the number of available features

**Comment by RoyWilliams** [comment]
22/JAN/25

0. Added latest OR as the priority task

1. Cutout image ingestion:  Cutouts will not be an issue after all, rather it is the catalogs

2. Sherlock: no news

3. ZTF in the DAC:  
    - ZTF ingestion of DR20 over a small area is complete. 
    - Two Lasair users interested -- Temple and Wiseman.
    - Can do this with Nublado notebook

4. Features:  
  
    - Features work is well-advanced. 
    - Astronomers in Oxford seemed pleased enough. 
    - Fastfinder is no longer part of Lasair, replace with BBB.

5. Profile and improve database resilience and scalability:

6. Performance Evaluation:

7. Add Fermi GBM alerts to GW infra:

8. Oxford meeting: 
 
    - Notes from Oxford meeting [here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3924623361/Notes+from+Rubin+Alerts+and+Brokers+Meeting)


9.  ZTF ops and maintenance - some PRs applied to Lasair ZTF (external brokers - lsst-uk/lasair4#230, URLs lsst-uk/lasair4#229). Need to apply these to Lasair-LSST too

    - a.   Lasair4 and ubuntu:  The task 10 has been moved to be a sub-task of this

**Comment by tms-epcc** [comment]
26/FEB/25
 2. a. Sherlock Delve and Gaia catalogues ingest done
 5. Performance Evaluation see [Cassandra  experiments writeup on wiki ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/4006313985/Cassandra+experiments)
 6. a. Integrated simulated alerts but schema has been changing
 7. Fermi GBM alerts 
     - distribution software being built by Eric Burns (NASA / GSFC) 
     -  had meeting with them   
     -  only want 1% of the alerts 
     -  needs further discussion with astronomers 
 9.  ZTF
    - upgrade to lasair ZTF OS 
    - next step is to make more nodes with multi-head DB for Lasair ZTF
    - then shutdown of ZTF old nodes and migrate to the new nodes. aiming to do this by end March

**Comment by RoyWilliams** [comment]
Cassandra experiments
https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/4006313985/Cassandra+experiments

**Comment by tms-epcc** [comment]
12/MAR/25
- [x] 0. Get ready for Operation Rehearsal 5, end of Feb

- [x] 1. Cutout image ingestion (@genghisken / @gpfrancis / @thespacedoctor )
    - [x] a. Reliability and optimisation
    - [x] b. Reaper for cutout images
    - [x] c.  How to fetch cutout images from Rubin (subject to availability)
  

see [Cassandra  experiments writeup on wiki ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/4006313985/Cassandra+experiments)

- [x] 9. Maintenance and continued operation of the ZTF pipeline, databases, and website
    - [x] a. Lasair4 maintenance issue - Migrating everything that is still on Ubuntu 20.04 to24.04 before April 2025. This needs specifically to be addressed in the next 6 months.   ( @gpfrancis )
